FW-1816 Registration Widget 1st pass (#472)
* useNavigationHelpers: duplicating methods from NavigationHelpers.js for use in Data components

- navigate: change url with pushWindowPath
- queryStringObject: returns query params as a js obj

* Changes to consume new GetTasksForUserGroupOperation endpoint

* Dashboard* DDCP

* WidgetPresentation

* Dashboard > Tasks

- Initial commit.  This is the view displayed when clicking from the Dashboard widget view into Dashboard > Tasks detail view

* WidgetTasks

- Widget displayed on Dashboard for Tasks
- Initial commit

* Styling for List variant ContentFullWidth

* New routes: Dashboard & Dashboard Tasks

* Setting Widget & List style variant: Full Width

* FW-1597 Tasks Widget

- removed unneeded code (eg: user registration)
- added isFetching & fetchMessage to data output
- Hiding Show All link in header if no data
- Setting `localization` prop for mat-table

* Prep for PR

Removed any non-task widget related code

* General cleanup before PR
- Drop unused code
- Add comment
- Add jsDocs

* Using constant name instead of value

* Item type constants

* TEMPLATE updates
- Added CSS
- Dropped most relative imports

* FW-1624 Dashboard Detail Presentation Components (tasks)

New components:
- DashboardDetail
- DashboardDetailIcon
- DashboardDetailList
- DashboardDetailListItem
- DashboardDetailSelectedItem

New Route: /dashboard/tasks

* TEMPLATE: Fixed broken import paths

* TEMPLATE: enabled dummy css

* Changed component name from List to Table
- Too confusing. Easily mistaken for a <ul>
- Updated imports & jsx tags

* Adjusting site typography to match a scale

* useNavigationHelpers

- Added navigateReplace & getSearchObject

* useUserGroupTasks

- initial pass

* useWindowPath added replaceWindowPath

* DashboardDetail updates

- Added a link to get to Dashboards
- selectedId prop added. Used to toggle selected/list view
- Bound escape press: closes selected item
- Split out sub-components into 3 children slots
- +2 event handlers: onOpen, onClose
- Deleted Container & Data. Should be implemented by component importing DashboardDetail

* DashboardDetailList

- Styling: refined border & header, added zebra stripes to mimic table
- Dropped DashboardDetailListData. Respoonsibility of component using DashboardDetailList
- added onClick 'row' handler

* DashboardDetailListItemPresentation

- zebra striping
- selected styling

* DashboardDetailSelectedItemPresentation

- Scrolls to top when new item loaded
- updated propTypes/jsDocs
- Using passed in props.icon

* - Added EVEN & ODD to Constants
- Using new constants in DashboardDetailListPresentation & DashboardDetailListItemPresentation
- DashboardDetailListItemPresentation has cursor:pointer when props.onClick defined

* DashboardDetailPresentation

- Fix issue where 'Show detail view' button is temporarily shown with some urls

* DashboardDetailTasks

- initial pass

* New route: /dashboard/tasks

* WidgetTasksData

- Using useUserGroupTasks DataSource

* /dashboard/tasks?active=first

- Will select the first item once the tasks data is received

* + gutterBottom to Typography elem

* Pagination added to Tasks Widget

- Note firing off a `fetch` request in *Data. Not using the Redux system we have in place.

* Widget Tasks: Sorting

* Upgrade material table

* Returning response objects to work with Material Table

* useUserGroupTasks updates

- added a flag that controls fetch on load
- increase DRY with formatTasksData
- return pagination related data

* Table: Sorting w/Remote Data workaround

- Using context to manage the sort direction
- Didn't want to include 'react-beautiful-dnd' so draggable is no longer supported
- Psuedo monkey-patch Material-Table. Lib supports `component override` so duplicated and fixed MTableHeader === TableHeader

* WidgetTasks updates

- Supports sort
- Using TableContextSort.Provider to set sortDirection
- Data layer working with both Redux XHR system & Mat-Table's Remote Data feature (ie: requires a promise to be provided)

* Upgrade babel to work with node v12.18.3

Encountered error:
`Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'`

* DashboardDetailSelectedItem updates
- Broke out 2 sub-components

* DashboardDetail
- moved a string to contants
- threading id to components that need it

* Words Core Component

Extracted a component that renders data on Words Detail. Planning to reuse it on Dashboard Detail.

* DashboardDetail

Added DetailWordPhrase.Presentation to DashboardDetail

* Sort & Pagination on Dashboard Detail view

- Moved TableContextSort.Provider into Data layers. Was too easy to miss this component when it was in the Container layer
- dropped the fetchOnLoad flag in useUserGroupTasks

* Added url queries: paging, sorting

- Need ids for selected task AND selected item
- Changed url query from `active` to `task`

* Widget Tasks: Additional url queries on `See All` link

* Widget Tasks

Test to show the 'See all tasks' doesn't work with 'remoteData'/Promises. Removed it.

* Adding url queries to WidgetTasks row click

* WidgetTasks row click url generation

- Page: compensate for mat-table zero-indexed page numbers
- Added default for sortBy

* Stop server requests with URL_QUERY_PLACEHOLDER

* Passing out the count

* Remove event handler from presentation layer

* Dashboard Detail > List pagination

- 1st pass

* Dashboard Detail > Selected Item: Pagination

* ROW CHANGE WORKING!

* useUserGroupTasks: Added resetTasks()

* Fixing bug transitioning from detail to table view

* Fixing pagination issues on Dashboard Widgets

* FW-576

- Needed to set the 'workspace' theme for /dashboard.
- Couldn't find an easy way of setting theme without using a specific url (eg: include workspace or sections in url)
- Updated this._route to check in matchedPage for `siteTheme`
- `siteTheme` is set in routes
- Used new system to fix FW-576
- Also fixed /tasks, it now has the workspaces theme

* Dashboard Detail: fixed date formatting

- custom hook is now formatting date
- so can drop the material-table `render()` prop that previously handled the formatting

* Delete file stubs

* RequestChanges: 1st round of integration

* RequestChangesData determines if dialect is published

* RequestChanges: fixed bug w/last selected visibility

- Using the `key` prop trick

Issue:
- Component doesn't unmount when clicking between list items
- Since it doesn't unmount, the previous select visibility value is used on the new selected item

* RequestChangesData: fix bug xhr sent with undef id

* useVisibility: now outputs extracted computeUpdateVisibility

* DashboardDetailTasks: onApproval event handler

- should trigger a list refresh
- anticipating incoming BE behaviour changes

* RequestChanges: approval flow updates

- now can handle server messages if an error is returned
- adds onApproval callback for external components that are wanting to be updated

* Setting docState with selected items

* Fixing pagination NaN value when logged out & on Dashboard page

* Dashboard Styling

Also includes:
- TablePagination: Fix issue with invalid nesting of tags
- TablePresentation: Fixed propType warning

* Initial Dashboard Detail styling

* Dashboard Detail: Reject Task using old endpoint

* Dashboard: Widget loading change

Stopped using `children` to support more than 1 widget. Using `widgets` prop instead

* TableHeader: dropping `width` calculated value

Using theme to set width instead

* WidgetRegistrations 1st pass

* Setting the 'See all' url

* WidgetRegistrationsData stub updates

- Fake server response based on /tasks output. Should be simiar when endpoint is available
- Formatting date
- More TODO comments
- Added data nomalizing for component in a .then(). Can move to data source later on

* Data Source: useRegistrations stub

- Moved fake responses from Data layer to Data Source
- Pagination controlled over in Data Source

* VisibilitySelect refactor

- Dropped mat ui classes system for plain old css classes
- Refined select list styling: icons are inline with text & vertically centered
- Added a `classes` prop to append custom css class names

* Deleting unused

* RequestChanges:
- removed somewhat identical class name
- Using VisibilitySelect.Presentation instead of Container. Container requires a computeEntities prop which doesn't work in this context. Don't need form validation props as well (due to no comments in this mvp)
- new css classes for styling purposes

* Rename: DashboardDetailList > DashboardDetailSidebar, DashboardDetailListItem > DashboardDetailSidebarItem

Note: includes WIP styling for the grid layout

* DashboardDetail: drop sub-components from index.js

* whitespace

* DashboardDetailPresentation: Comments

* DashboardDetail css layout

Got a good solution using a combination of grids & flexbox

* DashboardDetail
 - Updated close button icon & postion

* DashboardDetailSelectedItem css
- Approve/Reject border/bg bette match designs

* DashboardDetailSidebar

- Header border better match designs
- Pagination freestyled to match spirit of designs

* DashboardDetail table tweaks

- Unselected pagination now full width, right aligned, & no bottom border
- emptyRowsWhenPaging: false fixes gap between pagination and items when rows/page is greater than items displayed

* Dropped unnecessary files